#!/bin/bash
# postinst script for vifros
#
# see: dh_installdeb(1)

set -u
set -e

# Add the vifros user/group to the system.
adduser --system --group vifros

# Change perms of log folder/files.
chown -R vifros.vifros /var/log/vifros

# Installs the needed global links provided by the inner packages.
LINK_SRC=/opt/vifros/node_modules/.bin

pushd ${LINK_SRC}
  for file in *; do
    if [ -L $file ]; then
      ln --symbolic --force --logical ${LINK_SRC}/$file /usr/local/sbin/$file
    fi
  done
popd

# Rebuilds the native addons that may be present.
pushd /opt/vifros
  npm rebuild
popd

# Start the API service. This will start both
# the API server and the REPL server.
# It is named vifros since it doesn't conflict with the vifros CLI.
start vifros

exit 0