#!/bin/bash
# prerm script for vifros
#
# see: dh_installdeb(1)

set -u
set -e

# Remove the vifros user/group to the system.
deluser --system --remove-home vifros

# Removes the installed global links provided by the inner packages.
rm -R /usr/local/sbin/vifros*

# Stop the API service.
stop vifros || true

exit 0
